/**
* This file is automatically generated by jsrepo.
* Do not edit this file manually.
*/

export const REGISTRY_ITEMS = [
	'active',
	'avatar-group',
	'button',
	'chat',
	'code',
	'confirm-delete-dialog',
	'copy-button',
	'emoji-picker',
	'field-set',
	'file-drop-zone',
	'image-cropper',
	'ipv4address-input',
	'is-mac',
	'language-switcher',
	'light-switch',
	'link',
	'meter',
	'modal',
	'nlp-date-input',
	'number-field',
	'password',
	'phone-input',
	'pm-command',
	'rename',
	'shortcut',
	'snippet',
	'star-rating',
	'stepper',
	'tags-input',
	'terminal',
	'theme-selector',
	'toc',
	'tree-view',
	'underline-tabs',
	'use-auto-scroll',
	'use-boolean',
	'use-clipboard',
	'use-frecency',
	'use-media',
	'use-promise',
	'use-toc',
	'window'
] as const;

export type RegistryItem = (typeof REGISTRY_ITEMS)[number];
