import { Output } from 'jsrepo/outputs';
import path from 'node:path';
import fs from 'node:fs';

export default function (): Output {
	return {
		output: async (buildResult, { cwd }) => {
			const filePath = path.join(cwd, 'src/lib/demos/index.ts');

			const demoNames = buildResult.items.flatMap((item) =>
				item.files
					.filter((file) => file.role === 'example')
					.map((file) => path.parse(file.path).name)
					.sort()
			);

			const fileContent = `/**
* This file is automatically generated by jsrepo.
* Do not edit this file manually.
*/

export const DEMOS = [
    ${demoNames.map((demo) => `\t'${demo}'`).join(',\n')}
] as const;

export type Demo = (typeof DEMOS)[number];
`;

			fs.writeFileSync(filePath, fileContent);
		},
		clean: async () => {}
	};
}
