/**
* This file is automatically generated by jsrepo.
* Do not edit this file manually.
*/

export const DEMOS = [
    'avatar-group.svelte',
'avatar-group-vertical.svelte'
] as const;

export type Demo = (typeof DEMOS)[number];
