/**
* This file is automatically generated by jsrepo.
* Do not edit this file manually.
*/

export const DEMOS = [
    'avatar-group',
'avatar-group-vertical',
'button',
'button-loading',
'button-on-click-promise',
'chat',
'code',
'code-copy-button',
'code-no-line-numbers',
'code-variants',
'code-highlight-lines',
'code-overflow',
'copy-button',
'copy-button-icon',
'copy-button-with-text',
'emoji-picker',
'emoji-picker-skin',
'emoji-picker-popover',
'emoji-picker-footer',
'emoji-picker-recents',
'field-set',
'field-set-destructive',
'file-drop-zone',
'file-drop-zone-form',
'image-cropper',
'image-cropper-square-preview',
'image-cropper-no-default-image',
'image-cropper-custom-trigger',
'image-cropper-custom-preview',
'ipv4address-input',
'ipv4address-input-placeholder',
'ipv4address-input-reactive',
'ipv4address-input-valid'
] as const;

export type Demo = (typeof DEMOS)[number];
