/**
* This file is automatically generated by jsrepo.
* Do not edit this file manually.
*/

export const DEMOS = [
    'avatar-group',
'avatar-group-vertical',
'button',
'button-loading',
'button-on-click-promise'
] as const;

export type Demo = (typeof DEMOS)[number];
